name: "Run Tests with Coverage"
description: "Executes linter and tests with coverage report"

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: npm ci
      shell: bash

    - name: Run linter
      run: npm run lint
      shell: bash

    - name: Run tests with coverage
      run: npm run test:coverage
      shell: bash
